blog/urls.py
from django.conf.urls import url
from . import views


app_name = 'blog'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),  # 首页
    url(r'^post/(?P<pk>[0-9]+)/$', views.PostDetailView.as_view(), name='detail'),  # 文章详情
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.ArchivesView.as_view(), name='archives'),  # 归档
    url(r'^category/(?P<pk>[0-9]+)/$', views.CategoryView.as_view(), name='category'),  # 分类
    url(r'^tag/(?P<pk>[0-9]+)/$', views.TagView.as_view(), name='tag'),  # 标签
    #url(r'^search/$', views.search, name='search'),  # 搜索
]

myblog/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from blog.feeds import AllPostsRssFeed


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('blog.urls')),
    url(r'', include('comments.urls')),
    url(r'^all/rss/$', AllPostsRssFeed(), name='rss'),
    url(r'^search/', include('haystack.urls')),
    url(r'^users/', include('users.urls')),
]

users/urls.py
from django.conf.urls import url
from . import views


app_name = 'users'
urlpatterns = [
    url(r'^login/$', views.Login, name="login"),
    url(r'^logout/$', views.Logout, name="logout"),
    url(r'^register/$', views.Register, name="register"),
    url(r'^reset/$', views.Reset, name="reset"),
    url(r'^forget_email/$', views.ForgetEmail, name="forget_email"),
    # url(r'^forget_confirm/$', views.ForgetConfirm, name='forget_confirm'),
    url(r'^forget_done/$', views.ForgetDone, name='forget_done'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
# Create your models here.


class VerifyCode(models.Model):
    CHOICE = [
        (0, '密码找回'),
        (1, '转账'),
        (2, '登录验证'),
    ]
    user = models.ForeignKey(User)
    code = models.CharField('验证码', max_length=10)
    type = models.IntegerField('类型', choices=CHOICE, default=0)
    is_valid = models.BooleanField('是否有效', default=1)
    active_time = models.DateTimeField('有效期', default=timezone.now)

    def __str__(self):
        return self.code

    class Meta:
        ordering = ['-id']

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.forms import ValidationError
from .models import VerifyCode
from django.utils import timezone

# 登录
class LoginForm(forms.Form):
    # 在大部分情况下，字段都具有一个合理的默认Widget。
    # 例如，默认情况下，CharField 具有一个TextInput Widget，它在HTML 中生成一个<input type="text">
    # attrs让widget 具有一些特殊的CSS 类。 可以指定‘type’ 属性使用的是新的输入类型
    # 这里使class的类型是form-control
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    # def clean(self):
    #     cleaned_data = super(LoginForm, self).clean()
    #     username = cleaned_data.get('username')
    #     password = cleaned_data.get('password')
    #
    #     def __init__(self, user, *args, **kwargs):
    #         self.user = user
    #         super(LoginForm, self).__init__(*args, **kwargs)
    #
    #     if self.user is False:
    #         raise forms.ValidationError("用户验证失败！")


# 注册
class RegisterForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    email = forms.CharField(widget=forms.EmailInput(attrs={'class': 'form-control'}))

    # 用来抛出错误
    def clean(self):
        cleaned_data = super(RegisterForm, self).clean()
        username = cleaned_data.get('username')  # 拿数据
        password1 = cleaned_data.get('password1')
        password2 = cleaned_data.get('password2')

        #  创建一个列表，将错误传入，以便同时显示错误
        error_list = list()
        if User.objects.filter(username=username).count():
            error_list.append(ValidationError("用户已存在！"))
        if password1 != password2:
            error_list.append(forms.ValidationError("输入密码不一致！"))
        if len(error_list):
            raise forms.ValidationError(error_list)


# 更改密码
class ResetForm(forms.Form):
    old_password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    new_password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    new_password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    def __init__(self, user, *args, **kwargs):
        self.user = user
        # 继承了之前的，同时也写入了自己的方法
        # 既能使用之前的，也能使用自己覆写的
        super(ResetForm, self).__init__(*args, **kwargs)

    def clean(self):
        clean_data = super(ResetForm, self).clean()
        old_password = clean_data.get('old_password')
        new_password1 = clean_data.get('new_password1')
        new_password2 = clean_data.get('new_password2')

        error_list = list()
        if self.user.check_password(old_password) is False:
            error_list.append(ValidationError("原密码错误！"))
        if new_password1 != new_password2:
            error_list.append(ValidationError("输入密码不一致！"))
        if len(error_list):
            raise forms.ValidationError(error_list)


#  找回密码-发送邮件
class Forget_emailForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))


# 找回密码-输入验证码
class Forget_codeForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    code = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))

    def clean(self):
        clean_data = super(Forget_codeForm, self).clean()
        username = clean_data.get('username')
        code = clean_data.get('code')
        password1 = clean_data.get('password1')
        password2 = clean_data.get('password2')

        error_list = list()
        if password1 != password2:
            error_list.append(forms.ValidationError("输入密码不一致！"))
        if code is None:
            error_list.append(forms.ValidationError("输入验证码错误！"))
        else:
            # verify_code = VerifyCode.objects.filter(code=code)
            user = User.objects.get(username=username)
            try:
                verify_code = user.verifycode_set.first()
                if  not verify_code_time(verify_code) or verify_code.code !=code or verify_code.type != 0 :
                    error_list.append(forms.ValidationError("输入验证码错误！"))
                verify_code.is_valid = 0
            except Exception:
                error_list.append(forms.ValidationError("输入验证码错误！"))
        if len(error_list):
            raise forms.ValidationError(error_list)


# 找回密码-重置密码
# class Forget_confirmForm(forms.Form):
#     password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))
#     password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))
#
#     def clean(self):
#         clean_data = super(Forget_confirmForm, self).clean()
#         password1 = clean_data.get('password1')
#         password2 = clean_data.get('password2')
#
#         if password1 != password2:
#             raise forms.ValidationError("输入密码不一致！")



def verify_code_time(code):
    if timezone.now() > code.active_time:
        code.is_valid = 0
        code.save()
        return 0
    return 1

users/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.models import User
from .forms import LoginForm, RegisterForm, ResetForm, Forget_emailForm, Forget_codeForm
from django.core.mail import send_mail
from django.conf import settings
import string
import random
from users.models import VerifyCode
from django.utils import timezone
import datetime
from django.db import models


# Create your views here.
# 登录
def Login(request):
    if request.user.is_authenticated:
        messages.warning(request, "请不要重复登陆!")
        return HttpResponseRedirect(reverse('blog:index'))
    context = dict()
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                messages.success(request, "欢迎！")
                return HttpResponseRedirect(reverse('blog:index'))
            else:
                messages.error(request, "用户验证失败！")
        else:
            messages.error(request, "输入错误！")
    form = LoginForm()
    context['form'] = form
    return render(request, 'users/login.html', context)


# def Login(request):
#     if request.user.is_authenticated:
#         messages.warning(request, "请不要重复登陆!")
#         return HttpResponseRedirect(reverse('blog:index'))
#     if request.method == "POST":
#         username = request.POST['username']
#         password = request.POST['password']
#         # 查找用户是否存在
#         user = authenticate(request, username=username, password=password)
#         if user is None:
#             # 失败
#             messages.error(request, "登陆失败!")
#             return HttpResponseRedirect(reverse('users:login'))
#         else:
#             login(request, user)
#             messages.success(request, "登陆成功!")
#             return HttpResponseRedirect(reverse('blog:index'))
#     return render(request, 'users/login.html')


# 登出
def Logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('blog:index'))


# 注册
def Register(request):
    context = dict()
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password1 = form.cleaned_data['password1']
            email = form.cleaned_data['email']
            user = User.objects.create_user(username, email, password1)
            messages.success(request, "注册成功，欢迎登录！")
            return HttpResponseRedirect(reverse('users:login'))
        else:
            context['form'] = form
            return render(request, 'users/register.html', context)
    form = RegisterForm()
    context['form'] = form
    return render(request, 'users/register.html', context)


# def Register(request):
#     if request.method == "POST":
#         username = request.POST['username']
#         password1 = request.POST['password1']
#         password2 = request.POST['password2']
#         email = request.POST['email']
#         if username and password1 and password2 and email is False:
#             messages.error(request, '输入不能为空！')
#             return HttpResponseRedirect(reverse('users:register'))
#         elif User.objects.filter(username=username).count():
#             # 用户已存在
#             messages.error(request, '用户已存在！')
#             return HttpResponseRedirect(reverse('users:register'))
#         elif password1 != password2:
#             messages.error(request, '密码不一致！')
#             return HttpResponseRedirect(reverse('users:register'))
#         else:
#             user = User.objects.create_user(username, email, password1)
#             messages.success(request, '注册成功，请登录！')
#             return HttpResponseRedirect(reverse('users:login'))
#     return render(request, 'users/register.html')


# 修改密码
def Reset(request):
    context = dict()
    user = request.user
    if request.method == "POST":
        # 表示request.POST是传给data的，不至于混淆，传参的问题
        form = ResetForm(data=request.POST, user=request.user)
        if form.is_valid():
            new_password1 = form.cleaned_data['new_password1']
            user.set_password(new_password1)
            user.save()
            messages.success(request, "密码修改成功，请重新登录！")
            logout(request)
            return HttpResponseRedirect(reverse('users:login'))
        else:
            context['form'] = form
            return render(request, 'users/reset.html', context)
    form = ResetForm(user=request.user)
    context['form'] = form
    return render(request, 'users/reset.html', context)


# def Reset(request):
#     if request.method == 'POST':
#         # 1、从前台拿到数据
#         username = request.POST['username']
#         old_password = request.POST['old_password']
#         new_password1 = request.POST['new_password1']
#         new_password2 = request.POST['new_password2']
#         # 2、检查前台数据
#         if username and old_password and new_password1 and new_password2 is False:
#             messages.error(request, '输入不能为空！')
#             return HttpResponseRedirect(reverse('users:reset'))
#         user = request.user
#         if user.check_password(old_password) is False:
#             messages.error(request, '原密码错误！')
#             return HttpResponseRedirect(reverse('users:reset'))
#         elif new_password1 != new_password2:
#             messages.error(request, '密码不一致！')
#             return HttpResponseRedirect(reverse('users:reset'))
#         else:
#             user.set_password(new_password1)
#             user.save()
#             messages.success(request, '密码修改成功！')
#             logout(request)
#             return HttpResponseRedirect(reverse('users:login'))
#     return render(request, 'users/reset.html')


# 找回密码-验证用户名
def ForgetEmail(request):
    context = dict()
    if request.method == "POST":
        form = Forget_emailForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            user = User.objects.filter(username=username)[0]
            verify_code = ''.join(random.sample(string.digits, 6))
            VerifyCode.objects.get_or_create(user=user, code=verify_code, type=0, is_valid=1,
                                            active_time=timezone.now()+datetime.timedelta(minutes=30))
            subject = '来自huxdemon博客的验证邮件'
            text_content = '你的用户名:' + username + ',验证码:'+verify_code
            send_mail(subject, text_content, settings.EMAIL_FROM, [user.email], html_message=text_content)
            return HttpResponseRedirect(reverse('users:forget_done'))
        else:
            context['form'] = form
            return render(request, 'users/forget_email', context)
    form = Forget_emailForm()
    context['form'] = form
    return render(request, 'users/forget_email.html', context)


# 找回密码-输入验证码
def ForgetDone(request):
    context = dict()
    if request.method == "POST":
        form = Forget_codeForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password1 = form.cleaned_data['password1']
            user = User.objects.filter(username=username)[0]
            user.set_password(password1)
            user.save()
            messages.success(request, "密码更改成功！")
            # verify_code = VerifyCode.objects.filter(code=code)[0]
            return HttpResponseRedirect(reverse('users:login'))
        else:
            context['form'] = form
            return render(request, 'users/forget_done.html', context)
    form = Forget_codeForm()
    context['form'] = form
    return render(request, 'users/forget_done.html', context)


# 找回密码-设新密码
# def ForgetConfirm(request):
#     user = request.user
#     context = dict()
#     if request.method == "POST":
#         form = Forget_confirmForm(request.POST)
#         if form.is_valid():
#             password = form.cleaned_data['password1']
#             user.set_password(password)
#             user.save()
#             messages.success(request, "密码修改成功！")
#             return HttpResponseRedirect(reverse('users:login'))
#         else:
#             context['form'] = form
#             return render(request, 'users/forget_confirm.html', context)
#     form = Forget_confirmForm()
#     context['form'] = form
#     return render(request, 'users/forget_confirm.html', context)

templates/users/forget_confirm.html
{% extends 'base.html' %}

{% block main %}
<form class="form-horizontal" style="margin-top:240px;" action="{% url 'users:forget_confirm' %}" method="post">
    {% if form.non_field_errors %}
    {% for error in form.non_field_errors %}
    <div class="alert alert-danger" role="alert">{{ error|escape }}
    </div>
    {% endfor %}
    {% endif %}
    {% csrf_token %}
    <h3>设置新密码</h3>
    <div class="form-group">
        <label class="col-sm-2 control-label">新密码</label>
        <div class="col-sm-10">
            {{ form.password1 }}
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-2 control-label">确认新密码</label>
        <div class="col-sm-10">
            {{ form.password2 }}
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-default">确认</button>
        </div>
    </div>
</form>
{% endblock %}

templates/users/forget_done.html
{% extends 'base.html' %}

{% block main %}
    <div class="flex-center">
        <div class="container">
            <div>
                <h3>验证码已经发送</h3>
                <p>
                    如果您输入的用户所对应的邮箱存在，设置密码的提示已经发送邮件给您，您将很快收到。
                </p>
                <p>
                    如果你没有收到邮件, 请确保您所输入的邮箱地址是正确的, 并检查您的垃圾邮件文件夹.
                </p>
            </div>
        </div>
    </div>
<form class="form-horizontal" style="margin-top:120px;" action="{% url 'users:forget_done' %}" method="post">
    {% if form.non_field_errors %}
    {% for error in form.non_field_errors %}
    <div class="alert alert-danger" role="alert">
        {{ error|escape }}
    </div>
    {% endfor %}
    {% endif %}
    {% csrf_token %}
    <h3>重置密码</h3>
    <div class="form-group">
        <label class="col-sm-2 control-label">用户名</label>
        <div class="col-sm-10">
            {{ form.username }}
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-2 control-label">新密码</label>
        <div class="col-sm-10">
            {{ form.password1 }}
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-2 control-label">确认密码</label>
        <div class="col-sm-10">
            {{ form.password2 }}
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-2 control-label">验证码</label>
        <div class="col-sm-10">
            {{ form.code }}
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-default">确认</button>
        </div>
    </div>
</form>
{% endblock %}

templates/users/forget_email.html
{% extends 'base.html' %}

{% block main %}
<form class="form-horizontal" style="margin-top:240px;" action="{% url 'users:forget_email' %}" method="post">
    {% if form.non_field_errors %}
    {% for error in form.non_field_errors %}
    <div class="alert alert-danger" role="alert">{{ error|escape }}
    </div>
    {% endfor %}
    {% endif %}
    {% csrf_token %}
    <h3>重置密码</h3>
    <div class="form-group">
        <label class="col-sm-2 control-label">用户名</label>
        <div class="col-sm-10">
            {{ form.username }}
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-default">确认</button>
        </div>
    </div>
</form>
{% endblock %}

templates/users/login.html
{% extends 'base.html' %}

{% block main %}

<form class="form-horizontal" style="margin-top:240px;" action="{% url 'users:login' %}" method="post">
    {% if form.non_field_errors %}
    {% for error in form.non_field_errors %}
    <div class="alert alert-danger" role="alert">{{ error|escape }}
    </div>
    {% endfor %}
    {% endif %}
    {% csrf_token %}
    <div class="form-group">
        <label class="col-sm-2 control-label">用户名</label>
        <div class="col-sm-10">
            {{ form.username }}
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-2 control-label">密码</label>
        <div class="col-sm-10">
            {{ form.password }}
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-default" id="submit">登录</button>
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <div class="unit-1-3 flex-right"><span><a href="{% url 'users:forget_email' %}">忘记密码？</a></span></div>
        </div>
    </div>
</form>
{% endblock %}

templates/users/register.html
{% extends 'base.html' %}

{% block main %}

<form class="form-horizontal" style="margin-top:240px;" action="{% url 'users:register' %}" method="post">
    {% if form.non_field_errors %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger" role="alert">{{ error|escape }}
        </div>
    {% endfor %}
    {% endif %}
    {% csrf_token %}
    <div class="form-group">
        <label class="col-sm-2 control-label">用户名</label>
        <div class="col-sm-10">

            {{ form.username }}
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-2 control-label">密码</label>
        <div class="col-sm-10">
            {{ form.password1 }}
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-2 control-label">确认密码</label>
        <div class="col-sm-10">
            {{ form.password2 }}
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-2 control-label">邮箱</label>
        <div class="col-sm-10">
            {{ form.email }}
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-default" id="submit">注册</button>
        </div>
    </div>
</form>
{% endblock %}

templates/users/reset.html
{% extends 'base.html' %}

{% block main %}
<form class="form-horizontal" style="margin-top:240px;" action="{% url 'users:reset' %}" method="post">
    {% if form.non_field_errors %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger" role="alert">{{ error|escape }}
        </div>
    {% endfor %}
    {% endif %}
    {% csrf_token %}
    <div class="form-group">
        <label class="col-sm-2 control-label">原密码</label>
        <div class="col-sm-10">
            {{ form.old_password }}
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-2 control-label">新密码</label>
        <div class="col-sm-10">
            {{ form.new_password1 }}
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-2 control-label">确认新密码</label>
        <div class="col-sm-10">
            {{ form.new_password2 }}
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-default" id="submit">确认</button>
        </div>
    </div>
</form>
{% endblock %}